from enum import IntEnum


class MetaField(IntEnum):
    MODEL_NAME = 0
    MODEL_HASH = 1
    POSITIVE_PROMPT = 10
    NEGATIVE_PROMPT = 11
    CLIP_SKIP = 12
    SEED = 20
    STEPS = 21
    CFG = 22
    SAMPLER_NAME = 23
    SCHEDULER = 24
    IMAGE_WIDTH = 30
    IMAGE_HEIGHT = 31
    EMBEDDING_NAME = 40
    EMBEDDING_HASH = 41
    LORA_MODEL_NAME = 50
    LORA_MODEL_HASH = 51
    LORA_STRENGTH_MODEL = 52
    LORA_STRENGTH_CLIP = 53
